---
title: "cn-graphs"
output: html_document
---

```{r}
#Figure 1
O20 %>% 
  group_by(cntot4f) %>% filter(cntot4f!="NA") %>% 
  mean_ci(tropes, wt=wgt, ci=.84) %>% 
  ggplot(., aes(x=cntot4f, y=mean, fill= cntot4f)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="G", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="G", nudge_y = -.6) +
  scale_y_continuous() +
  labs(x="Level of Christian Nationalism", y="Average Number of\nTropes People Agree With", 
       title=NULL,
       caption="Source: October 2020 Survey") +
  scale_fill_manual(values=c("#3F4041","#3F4041","#3F4041","#3F4041"))

```


```{r}
#Figure 2

O20_tropes %>% 
  group_by(t_tropes, cntot4f) %>% 
  ct(p_tropes, wt=wgt) %>% 
  filter(p_tropes==1) %>% 
  ggplot(., aes(x=cntot4f, y=pct, fill= cntot4f)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  theme_hc() +
  theme(text=element_text(family="G", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(pct * 100, digits = 2)), family="G", nudge_y = -.07, size=3.5, color="white") +
  scale_y_continuous(labels=percent_format(accuracy=1)) +
  labs(x="Level of Christian Nationalism", 
       y="Percentage of Respondents Who\nAgree with Each Statement", 
       title=NULL,
       caption="Source: October 2020 Survey") +
  scale_fill_manual(values=c("#3F4041","#3F4041","#3F4041","#3F4041"))+
  facet_wrap(~t_tropes)

```



```{r}
#Figure 3

O20_tropes %>% group_by(t_tropes, q38_10lab, cntot4f) %>% 
  ct(p_tropes, wt=wgt) %>% filter(p_tropes==1) %>% 
  ggplot(., aes(x=cntot4f, y=pct, color=q38_10lab, group=q38_10lab)) +
  geom_line(size=1.25) +
  geom_point(size=4, color="white", shape=19) +
  geom_point(size=4, shape=1) +
  theme_hc() +
  facet_wrap(~t_tropes, ncol=4, nrow=2) +
  theme(legend.position="bottom",
        text=element_text(family="G", size=12),        
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  scale_x_discrete(labels=c("Lowest", "", "", "Highest")) +
  scale_y_continuous(labels=percent_format(accuracy=1)) +
  labs(x="Level of Christian Nationalism", 
       y="Percentage of Respondents Who\nAgree with Each Statement",
       caption="Source: October 2020 Survey.",
       title=NULL) +
  scale_color_manual(values = c("#84D7E1FF", "#8A4198FF"), name="QAnon Belief")

```

```{r}
O20 %>% 
  group_by(hiattf, reltrad) %>% filter(hiattf!="NA") %>% 
  filter(reltrad!="Jewish") %>% 
  mean_ci(tropes, wt=wgt, ci=.84) %>% 
  ggplot(., aes(x=hiattf, y=mean, fill= hiattf)) + 
  geom_col(alpha=.8, color="black", width = .75) + 
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1) +
  theme_hc() +
  theme(text=element_text(family="G", size=12),
        legend.position = "blank",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = round(mean, digits=2)), family="G", nudge_y = 1) +
  scale_y_continuous() +
  labs(x="Church Attendance", y="Average Number of\nTropes People Agree With", 
       title=NULL,
       caption="Source: October 2020 Survey") +
  scale_fill_manual(values=c("#3F4041","#3F4041","#3F4041","#3F4041","#3F4041","#3F4041")) +
  facet_wrap(~reltrad, nrow=2)

```

```{r}
cn_hiattf <- glm.nb(tropes ~ cn*attend5*white+q38_10rc+sdo+cphavg+evil+pid7f+age+female+ed+reltrad, 
                   data = O20, weight=wgt)

interact_plot(cn_hiattf, pred = cn, modx = attend5, mod2=white,
              int.width=.76, interval = TRUE,               
              modx.values = "plus-minus",
              modx.labels = c("Low","High"),
              mod2.labels = c("Non-White", "White"),
              colors = c("#84D7E1FF", "#8A4198FF"),
              legend.main = "Church Attendance") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Level of Christian Nationalism", 
       y="Percentage of Respondents Who\nAgree with Each Statement", 
       title=NULL,
       caption="Source: October 2020 Survey") +
  scale_y_continuous()



```



```{r}

cn_cphavg <- glm.nb(tropes ~ cn*cphavg*white+q38_10rc+sdo+attend5+evil+pid7f+age+female+ed+reltrad, 
                   data = O20, weight=wgt)
interact_plot(cn_cphavg, pred = cn, modx = cphavg, mod2=white,
              int.width=.76, interval = TRUE,
              modx.values = "plus-minus",
              modx.labels = c("Low","High"),
              mod2.labels = c("Non-White", "White"),
              colors = c("#84D7E1FF", "#8A4198FF"),
              legend.main = "Level of Perceived\nChristian Persecution") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Level of Christian Nationalism", 
       y="Percentage of Respondents Who\nAgree with Each Statement", 
       title=NULL,
       caption="Source: October 2020 Survey") +
  scale_y_continuous()

```


```{r}
cn_qanon <- glm.nb(tropes ~ cn*q38_10rc*white+attend5+sdo+cphavg+evil+pid7f+age+female+ed+reltrad, 
                   data = O20, weight=wgt)

interact_plot(cn_qanon, pred = cn, modx = q38_10rc, mod2=white,
              int.width=.76, interval = TRUE,
              modx.values=c(0,1),
              modx.labels = c("Disagree","Agree"),
              mod2.labels = c("Non-White", "White"),
              colors = c("#84D7E1FF", "#8A4198FF"),
              legend.main = "QAnon") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Level of Christian Nationalism", 
       y="Percentage of Respondents Who\nAgree with Each Statement", 
       title=NULL,
       caption="Source: October 2020 Survey") +
  scale_y_continuous()




```

```{r}
cn_sdo <- glm.nb(tropes ~ cn*sdo*white+q38_10rc+cphavg+attend5+evil+pid7f+age+female+ed+reltrad, 
                   data = O20, weight=wgt)
interact_plot(cn_sdo, pred = cn, modx = sdo, mod2=white,
              int.width=.76, interval = TRUE,
              modx.values = "plus-minus",
              modx.labels = c("Low", "High"),
              mod2.labels = c("Non-White", "White"),
              colors = c("#84D7E1FF", "#8A4198FF"),
              legend.main = "Level of Social\nDominance\nOrientation") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Level of Christian Nationalism", 
       y="Percentage of Respondents Who\nAgree with Each Statement", 
       title=NULL,
       caption="Source: October 2020 Survey") +
  scale_y_continuous()

```



```{r}
#make a plot summs graph for the model

cn_model <- glm.nb(tropes ~ cn+sdo+q38_10rc+cphavg+attend5+evil+white+pid7f+age+female+ed+reltrad, 
                   data = O20, weight=wgt)

plot_summs(cn_model,
           coefs = c("Christian Nationalism"="cn",
                     "Social Dominance Orientation"="sdo",
                     "QAnon"="q38_10rc",
                     "Christian Persecution"="cphavg",
                     "Church Attendance"="attend5",
                     "Belief in Evil"="evil",
                     "White"="white",
                     "Democrat"="pid7fDemocrat",
                     "Lean Democrat"="pid7fLean\nDemocrat",
                     "Independent"="pid7fIndependent",
                     "Lean Republican"="pid7fLean\nRepublican",
                     "Republican"="pid7fRepublican",
                     "Strong Republican"="pid7fStrong\nRepublican",
                     "Age"="age",
                     "Female"="female",
                     "Education Level"="ed",
                     "Mainline"="reltradMainline",
                     "Black Protestant"="reltradBlack Prot.",
                     "Catholic"="reltradCatholic",
                     "Jewish"="reltradJewish",
                     "Other Faith"="reltradOther Faith",
                     "Non-Denominational"="reltradNon-Denominational",
                     "Unclassified"="reltradUnclassified"),
           ci_level = 0.84) +
  theme_minimal()+
  theme(text=element_text(family="G", size=12),
          panel.grid.major.y = element_blank())+
  labs(x="Estimate",
       y=NULL,
       title = NULL)



```

```{r}
cn_fd <- glm.nb(p_fd_o20 ~ cn+t_fd_o20+attend5+sdo+q38_10rc+cphavg+evil+white+pid7f+age+female+ed+reltrad, 
                   data = O20_fd, weight=wgt)
summary(cn_fd)

interact_plot(cn_fd, pred = cn, modx = t_fd_o20, 
              int.width=.76, interval = TRUE,
              colors = c("#84D7E1FF", "#8A4198FF"),
              legend.main = "") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Level of Christian Nationalism", 
       y="Support for Fighting Discrimination",
       title=NULL)+
  scale_y_continuous()

```


```{r}
att_fd <- glm.nb(p_fd_o20 ~ cn+t_fd_o20*attend5+sdo+q38_10rc+cphavg+evil+white+pid7f+age+female+ed+reltrad, 
                   data = O20_fd, weight=wgt)
summary(att_fd)

interact_plot(att_fd, pred = attend5, modx = t_fd_o20, 
              int.width=.76, interval = TRUE,
              colors = c("#84D7E1FF", "#8A4198FF"),
              legend.main = "") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Church Attendance\n(Higher number is greater attendance)", 
       y="Support for Fighting Discrimination",
       title=NULL)+
  scale_y_continuous()

```


```{r}
sdo_fd <- glm.nb(p_fd_o20 ~ cn+t_fd_o20*sdo+attend5+q38_10rc+cphavg+evil+white+pid7f+age+female+ed+reltrad, 
                   data = O20_fd, weight=wgt)
summary(sdo_fd)

interact_plot(sdo_fd, pred = sdo, modx = t_fd_o20, 
              int.width=.76, interval = TRUE,
              colors = c("#84D7E1FF", "#8A4198FF"),
              legend.main = "") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="SDO Level", 
       y="Support for Fighting Discrimination",
       title=NULL)+
  scale_y_continuous()

```

```{r}
cph_fd <- glm.nb(p_fd_o20 ~ cn+t_fd_o20*cphavg+sdo+attend5+q38_10rc+evil+white+pid7f+age+female+ed+reltrad, 
                   data = O20_fd, weight=wgt)
summary(cph_fd)

interact_plot(cph_fd, pred = cphavg, modx = t_fd_o20, 
              int.width=.76, interval = TRUE,
              colors = c("#84D7E1FF", "#8A4198FF"),
              legend.main = "") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="CPH Level", 
       y="Support for Fighting Discrimination",
       title=NULL)+
  scale_y_continuous()

```

```{r}
evil_fd <- glm.nb(p_fd_o20 ~ cn+t_fd_o20*evil+sdo+attend5+q38_10rc+cphavg+white+pid7f+age+female+ed+reltrad, 
                   data = O20_fd, weight=wgt)
summary(evil_fd)

interact_plot(evil_fd, pred = evil, modx = t_fd_o20, 
              int.width=.76, interval = TRUE,
              colors = c("#84D7E1FF", "#8A4198FF"),
              legend.main = "") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Evil Active", 
       y="Support for Fighting Discrimination",
       title=NULL)+
  scale_y_continuous()

```


```{r}
cph_az <- glm.nb(p_az_o20 ~ cn+t_az_o20*cphavg+tropes+attend5+sdo+end+q38_10rc+evil+white+pid7f+age+female+ed+reltrad, 
                   data = O20_az, weight=wgt)
summary(cph_az)

interact_plot(cph_az, pred = cphavg, modx = t_az_o20, 
              int.width=.76, interval = TRUE,
              colors = c("#FF6F00FF", "#8A4198FF", "#84D7E1FF"),
              legend.main = "") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Belief that Christians Are Being Persecuted", 
       y="Support for Self-Determination",
       title="Higher Belief in Christian Persecution Increases Support Zionism")+
  scale_y_continuous()

```

```{r}
tr_az <- glm.nb(p_az_o20 ~ tropes*t_az_o20+attend5+cphavg+sdo+q38_10rc+end+cn+evil+white+pid7f+age+female+ed+reltrad, 
                   data = O20_az, weight=wgt)
summary(tr_az)

interact_plot(tr_az, pred = tropes, modx = t_az_o20, 
              int.width=.76, interval = TRUE,
              colors = c("#FF6F00FF", "#8A4198FF", "#84D7E1FF"),
              legend.main = "") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Number of Antisemitic Tropes Agreed With", 
       y="Support for Self-Determination\n(Higher Number means more support)",
       title="Antisemites Are Not Inherently Anti-Zionist, In Fact It Might Be the Opposite")+
  scale_y_continuous()

```

```{r}
end_az <- glm.nb(p_az_o20 ~ end*t_az_o20+attend5+cphavg+sdo+q38_10rc+tropes+cn+evil+white+pid7f+age+female+ed+reltrad, 
                   data = O20_az, weight=wgt)
summary(end_az)

interact_plot(end_az, pred = end, modx = t_az_o20, 
              int.width=.76, interval = TRUE,
              colors = c("#FF6F00FF", "#8A4198FF", "#84D7E1FF"),
              legend.main = "") +
  theme_minimal() +
  theme(text=element_text(family="G", size=12),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(size=.5, color="gray80"),
        legend.position = "right",
        plot.title = element_text(hjust = .5),
        legend.title = element_text(hjust = .5)) +
  labs(x="Belief that the End Times Are Near", 
       y="Support for Self-Determination\n(Higher Number means more support)",
       title="Antisemites Are Not Inherently Anti-Zionist, In Fact It Might Be the Opposite")+
  scale_y_continuous()

```







